### ISSUE TITLE
Add debounce utility function

### ISSUE THREAD

**Issue by robert-s-hogan** [robert-s-hogan/nx-monorepo#103]
## Description
- Implement a debounce utility function to limit the rate at which a function can be called.

## Tasks
- [ ] Define the debounce function signature.
- [ ] Implement the debounce function.
- [ ] Add unit tests for debounce.
- [ ] Update documentation with examples of usage.

## Acceptance Criteria
- The debounce function should accept a function and a delay as input.
- The debounce function should return a debounced version of the input function.
- The debounced function should only be invoked after the specified delay has elapsed since the last call.
